# Generated by Django 5.0.1 on 2024-01-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heladera',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
