# Generated by Django 5.0.1 on 2024-01-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladera', '0003_heladera_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heladera',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
