# Generated by Django 5.0.1 on 2024-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladera', '0004_alter_heladera_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heladera',
            old_name='liters',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='heladera',
            name='weight',
        ),
        migrations.AddField(
            model_name='heladera',
            name='unit',
            field=models.CharField(blank=True, choices=[('LT', 'Litros'), ('KG', 'Kilogramos')], max_length=2, null=True),
        ),
    ]
